# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  env_repo_prep:
    name: checkout and setup jdk
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
        
  build:
    name: gradle build
    runs-on: ubuntu-latest
    steps:
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
      
  test:
    name: gradle cleantest with datadog ci vis enabled
    runs-on: ubuntu-latest
    steps:
    - name: Test with Gradle
      run: DD_CIVISIBILITY_AGENTLESS_ENABLED=true DD_API_KEY=${{ secrets.DD_API_KEY }} DD_ENV=ci ./gradlew cleanTest test -Pdd-civisibility --rerun-tasks

  docker_build_push:
    name: build and push docker image to docker repo
    runs-on: ubuntu-latest
    steps:
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: jonlimpw/demo-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
